apiVersion: batch/v1
kind: Job
metadata:
  name: scanner-job
spec:
  ttlSecondsAfterFinished: 20
  template:
    spec:
      containers:
        - name: scanner-job
          image: avshiliaev/job:0.0.1
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4

